### ISSUE TITLE
ERROR: Could not build wheels for libterraform which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by judab5ericom** [Prodesire/py-terraform#3]
getting the following error when trying to compile local
 Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
/home/judab/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/judab/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Building wheels for collected packages: libterraform
  Building wheel for libterraform (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpjxsbgvg0 build_wheel /tmp/tmpmuv6vjmq
       cwd: /tmp/pip-req-build-4kwbn1bw
  Complete output (33 lines):
  # sigs.k8s.io/json/internal/golang/encoding/json
  /home/judab/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
  /home/judab/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
        - Patching go-plugin package
        - Building libterraform
  Traceback (most recent call last):
    File "build.py", line 72, in <module>
      build({})
    File "build.py", line 54, in build
      subprocess.check_call(
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['go', 'build', '-buildmode=c-shared', '-o=libterraform.so', 'github.com/hashicorp/terraform']' returned non-zero exit status 2.
  Traceback (most recent call last):
    File "/tmp/tmpjxsbgvg0", line 280, in <module>
      main()
    File "/tmp/tmpjxsbgvg0", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpjxsbgvg0", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-e48g7589/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/tmp/pip-build-env-e48g7589/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 78, in make_in
      wb.build()
    File "/tmp/pip-build-env-e48g7589/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 106, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-e48g7589/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 152, in _build
      self._run_build_script(self._package.build_script)
    File "/tmp/pip-build-env-e48g7589/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 202, in _run_build_script
      subprocess.check_call([self.executable.as_posix(), build_script])
    File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python3', 'build.py']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for libterraform
Failed to build libterraform
ERROR: Could not build wheels for libterraform which use PEP 517 and cannot be installed directly

**Comment by Prodesire** [comment]
@judab5ericom Sorry for the late reply. From the above description, the reason for the failure is: 
> /home/judab/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
  /home/judab/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)

You can refer to the solution mentioned in [the similiar issue](https://github.com/kubernetes-sigs/controller-tools/issues/643), which is to update the version of golang.
